config/routes.rb
Rails.application.routes.draw do
  
  resources :advertisements
  root to: "advertisements#index"
  
  get '/id:id' => 'users#show', as: 'user'
  get '/users/coords' => 'coords'
  
  get '/responses' => 'responses#index', as: 'responses'
  get '/responses/new/:id' => 'responses#new', as: 'new_response'
  post '/responses/:id' => 'responses#create', as: 'response'
  delete '/responses/:id' => 'responses#destroy'
  
  devise_for :users, controllers: {
    confirmations: "users/confirmations",
    omniauth_callbacks: "users/omniauth_callbacks",
    passwords:     "users/passwords",
    registrations: "users/registrations",
    sessions:      "users/sessions"
  }
  
end

app/models/advertisement.rb
class Advertisement < ActiveRecord::Base
  belongs_to :user
  has_many :responses
  validates :text, presence: true
  has_attached_file :image, default_url: "missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/advertisements_controller.rb
class AdvertisementsController < ApplicationController
  before_action :authenticate_user!, only: [:show, :edit, :update, :new, :create, :destroy]
  before_action :set_advertisement,  only: [:show, :edit, :update, :destroy]

  def index
    @advertisements = Advertisement.paginate(:page => params[:page], :per_page => 5).order('updated_at DESC')
  end

  def show
  end

  def new
    @advertisement = Advertisement.new
  end

  def edit
  end
  
  def create
    @advertisement = Advertisement.new(advertisement_params)
    @advertisement.user_id = current_user.id

    respond_to do |format|
      if @advertisement.save
        format.html { redirect_to advertisements_path, notice: 'Advertisement was successfully created.' }
        #format.json { render :show, status: :created, location: @advertisement }
      else
        format.html { render :new }
        #format.json { render json: @advertisement.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @advertisement.user_id = current_user.id && @advertisement.update(advertisement_params)
        format.html { redirect_to advertisements_path, notice: 'Advertisement was successfully updated.' }
        #format.json { render :show, status: :ok, location: @advertisement }
      else
        format.html { render :edit }
        #format.json { render json: @advertisement.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @advertisement.user_id = current_user.id
      @advertisement.destroy
      respond_to do |format|
        format.html { redirect_to advertisements_url, notice: 'Advertisement was successfully destroyed.' }
        #format.json { head :no_content }
      end
    end
  end

  private
  
    def set_advertisement
      @advertisement = Advertisement.find(params[:id])
    end

    def advertisement_params
      params.require(:advertisement).permit(:text, :image)
    end
end

app/helpers/advertisements_helper.rb
module AdvertisementsHelper
end

app/views/advertisements/_form.html.haml
%h2
= form_for(@advertisement) do |f|
    
  .field.mdl-textfield.mdl-js-textfield
    .mdl-textfield__label
      = f.label :text
    %br/
    .mdl-textfield__input
      = f.text_area :text, autofocus: true
  %br/
  .field.mdl-textfield.mdl-js-textfield
    .mdl-textfield__label
      = f.label :image
    %br/
    .mdl-textfield__input
      = f.file_field :image
  %br/
  = f.submit @submit, class: "button mdl-js-button"

app/views/advertisements/_textile.text.erb
<%= RedCloth.new(@advertisement.text).to_html %>

app/views/advertisements/edit.html.haml
.mdl-grid
  .mdl-cell.mdl-cell--1-col.mdl-cell--1-col-tablet.mdl-cell-1-col-phone
  .mdl-cell.mdl-cell--5-col.mdl-cell--3-col-tablet.mdl-cell-3-col-phone
    %h1 Editing Advertisement
    -@submit="Update"
    = render 'form'
    = link_to 'Show', @advertisement
    |
    = link_to 'Back', advertisements_path

app/views/advertisements/index.html.haml
.mdl-grid
  .mdl-cell.mdl-cell--1-col.mdl-cell--1-col-tablet.mdl-cell--hide-phone
  .mdl-cell.mdl-cell--8-col.mdl-cell--4-col-tablet.mdl-cell-4-col-phone
    %h1 Advertisements
    
    = link_to 'New Advertisement', new_advertisement_path
    %br/
    = will_paginate @advertisements
    - @advertisements.each do |advertisement|
      -@advertisement = advertisement
      .ad
        = render :partial => "textile.text.erb"
        %br/
        %b by user: 
        = @advertisement.user.login
        %br/
        =image_tag @advertisement.image.url, class: "thumb"
        %br/
        = link_to 'Show', advertisement
        -if advertisement.user == current_user  
          = link_to 'Edit', edit_advertisement_path(advertisement)
          = link_to 'Destroy', advertisement, method: :delete, data: { confirm: 'Are you sure?' }
        -else
          - @ad_id = @advertisement.id
          - @response = Response.new()
          - jstr = "response('#advertisement_#{@ad_id}')"
          = link_to "Response", "#", onclick: jstr, class: "response-button"
          .response-form[@advertisement]
            = render 'responses/form'
        %br/
    = will_paginate @advertisements
    %br/
    
:javascript
  $(document).ready(function(){
    $('.advertisement').hide();
  });
  
  $("body").click( function(e){
    if($(e.target).parents('.advertisement').length != 1 && 
            e.target.className != "advertisement" &&
            e.target.className != "response-button")
    {
      $('.advertisement').hide();
    }
  });
  
  function response(id){
    $('.advertisement').hide();
    $(id).show();
  }

app/views/advertisements/new.html.haml
.mdl-grid
  .mdl-cell.mdl-cell--1-col.mdl-cell--1-col-tablet.mdl-cell--hide-phone
  .mdl-cell.mdl-cell--8-col.mdl-cell--4-col-tablet.mdl-cell-4-col-phone
    %h1 New Advertisement
    -@submit="Post"
    = render 'form'
    = link_to 'Back', advertisements_path

app/views/advertisements/show.html.haml
.mdl-grid
  .mdl-cell.mdl-cell--1-col.mdl-cell--1-col-tablet.mdl-cell--hide-phone
  .mdl-cell.mdl-cell--8-col.mdl-cell--4-col-tablet.mdl-cell-4-col-phone
    .ad
      %p
        %strong Text:
        = render :partial => "textile.text.erb"
      %p
        %strong User:
        = @advertisement.user.login
      =image_tag @advertisement.image.url, class: "img-medium"
      %br/
      - if current_user == @advertisement.user
        = link_to 'Edit', edit_advertisement_path(@advertisement)
      - else
        = link_to 'Response', new_response_path(@advertisement.id) 
      = link_to 'Back', advertisements_path
      