config/routes.rb
Rails.application.routes.draw do
  
  resources :advertisements
  root to: "advertisements#index"
  
  get '/id:id' => 'users#show', as: 'user'
  get '/users/coords' => 'coords'
  
  get '/responses' => 'responses#index', as: 'responses'
  get '/responses/new/:id' => 'responses#new', as: 'new_response'
  post '/responses/:id' => 'responses#create', as: 'response'
  delete '/responses/:id' => 'responses#destroy'
  
  devise_for :users, controllers: {
    confirmations: "users/confirmations",
    omniauth_callbacks: "users/omniauth_callbacks",
    passwords:     "users/passwords",
    registrations: "users/registrations",
    sessions:      "users/sessions"
  }
  
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  before_action :set_response, only: [:destroy]
  before_action :authenticate_user!

  def index
  	@responses = Response.where(addressee:current_user)
    @responses = @responses.paginate(:page => params[:page], :per_page => 5).order('updated_at DESC')
  end

  def new
  	@ad_id = params[:id]
  	if current_user == Advertisement.find(@ad_id).user
  		redirect_to root_path
  	else
      @response = Response.new
    end
  end

  def create
  	if current_user == Advertisement.find(params[:id]).user
  		redirect_to root_path
  	else
      @response = Response.new
      @response.content = (response_params)["content"]
      @response.advertisement = Advertisement.find(params[:id])
      @response.addressee = Advertisement.find(params[:id]).user.id
      @response.user=current_user

      if @response.save
      	redirect_to @response.advertisement
      else
        render :new
      end
    end
  end

  def destroy
  	if current_user.id == @response.addressee
  		@response.destroy
  	end
  	redirect_to root_path
  end

  private
  
    def set_response
      @response = Response.find(params[:id])
    end

    def response_params
      params.require("response").permit("content")
    end
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/views/responses/_form.html.haml
= form_tag(response_path(@ad_id), method: "post") do
  - if @response.errors.any?
    #error_explanation
      %h2
        = pluralize(@response.errors.count, "error")
        prohibited this response from being saved:
      %ul
        - @response.errors.full_messages.each do |message|
          %li= message
  .field
    = label_tag("response[content]", "Your response:")
    %br/
    = text_area_tag("response[content]")
    %br/
    = submit_tag("Send")
    %br/

app/views/responses/index.html.haml
.mdl-grid
  .mdl-cell.mdl-cell--4-col.mdl-cell--1-col-tablet.mdl-cell--hide-phone
  .mdl-cell.mdl-cell--6-col.mdl-cell--6-col-tablet.mdl-cell-4-col-phone
    %h1 Your Responses
    = will_paginate @responses

    - @responses.each do |response|
      .ad
        %br/
        %b from user 
        = response.user.login
        %br/
        = response.content
        %br/
        = link_to 'Your Ad ', advertisement_path(response.advertisement)
        %br/
        = link_to 'Destroy', response, method: :delete, data: { confirm: 'Are you sure?' }
        %br/
    = will_paginate @responses
    %br/

app/views/responses/new.html.haml
.mdl-grid
  .mdl-cell.mdl-cell--4-col.mdl-cell--1-col-tablet.mdl-cell--hide-phone
  .mdl-cell.mdl-cell--6-col.mdl-cell--6-col-tablet.mdl-cell-4-col-phone
    %h1 New Response
    = render 'form'
    = link_to 'Back', responses_path

app/views/responses/show.html.haml
.mdl-grid
  .mdl-cell.mdl-cell--4-col.mdl-cell--1-col-tablet.mdl-cell--hide-phone
  .mdl-cell.mdl-cell--6-col.mdl-cell--6-col-tablet.mdl-cell-4-col-phone
    %p
      %strong Content:
      = @response.content
    %p
      %strong User:
      = @response.user
    %p
      %strong Advertisement:
      = @response.advertisement
    = link_to 'Edit', edit_response_path(@response)
   |
    = link_to 'Back', responses_path